org: btaratruhandarien
app: steth-tracker
service: steth-scheduled-tracker

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  stethScheduledTracker:
    handler: handler.run
    events:
      # Invoke Lambda function on every 12 PM
      - schedule:
          name: steth-tracker-schedule
          description: 'Schedule to run tracker for stETH rebalancing'
          # steth rebalancing happens at 07.00 UTC time
          rate: cron(0 12 * * * *)
      - schedule:
          name: steth-tracker-schedule-offline
          enabled: false
          description: 'Schedule when running tracker locally'
          rate: cron(0/5 * * * * *)

plugins:
  - serverless-dotenv-plugin
  - serverless-offline-schedule
